name: OSRS Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  scrape:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit updated JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add money_methods.json
          git commit -m "Update methods" || echo "No changes"
          git push
