name: OSRS Scraper

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run wiki scraper
        run: python scraper.py

      - name: Run profit engine
        run: python profit_engine.py

      - name: Commit JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add money_methods.json
          git commit -m "Update JSON" || echo "No changes"
          git push
